### ISSUE TITLE
5th March 2019 News

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/meetup-news#1]

**Comment by kevbite** [comment]
13th Feb 2019 - Blazor Released @ 0.8.0

**Comment by kevbite** [comment]
January 29, 2019 - .NET Core 3 Preview 2 Announced https://blogs.msdn.microsoft.com/dotnet/2019/01/29/announcing-net-core-3-preview-2/
This includes C# 8 Preview 2

**Comment by kevbite** [comment]
5th Feb 2019 - ML.NET v0.10 Released @ 0.10.0 https://github.com/dotnet/machinelearning

**Comment by kevbite** [comment]
DDD Events:
DDD East Midlands - Call for Speakers Open, Closes 27th April
DDD South West - Session Voting Opens - Saturday 9th March
DDD South West - Registration Opens - Saturday 30th March 2019

**Comment by kevbite** [comment]
Visual Basic’s File IO Added to .NET Core 😂 
Includes lots of APIs like moving files to recycle bin etc... 
Will be "cross-platform" except for things that won't be and will throw a `PlatformNotSupported` exception

**Comment by mssteele** [comment]
Visual Studio 2019 Launch Event is on Tuesday 2nd April - same day as April's meetup
 https://visualstudio.microsoft.com/vs2019-launch/
