### ISSUE TITLE
2nd April 2019 News

### ISSUE THREAD

**Issue by mssteele** [dotnetsheff/meetup-news#2]

**Comment by mssteele** [comment]
Big one this month: Microsoft open-sources its Windows calculator on GitHub
https://www.theverge.com/2019/3/6/18253474/microsoft-windows-calculator-open-source-github

**Comment by kevbite** [comment]
Azure DevOps Server has been released 
https://azure.microsoft.com/en-gb/blog/now-available-azure-devops-server-2019/

**Comment by sakisk** [comment]
Announcing the Open Sourcing of Windows Calculator https://blogs.windows.com/buildingapps/2019/03/06/announcing-the-open-sourcing-of-windows-calculator/

**Comment by kevbite** [comment]
Blazor 0.9 released - https://devblogs.microsoft.com/aspnet/blazor-0-9-0-experimental-release-now-available/

**Comment by kevbite** [comment]
SQL in the City Summit
 - https://www.red-gate.com/hub/events/redgate-events/sqlinthecity-summit/london

Discount code - Community19

**Comment by sakisk** [comment]
.NET Foundation Board of directors
https://dotnetfoundation.org/blog/2019/03/28/net-foundation-board-of-directors-election-results

**Comment by sakisk** [comment]
.NET Core 3.0 preview 3 announced
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-3/

**Comment by sakisk** [comment]
.NET Core Workers as Windows Services

`dotnet new worker`

https://devblogs.microsoft.com/aspnet/net-core-workers-as-windows-services/
